# Generated by Django 5.2 on 2025-04-25 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_contas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('icone', models.CharField(max_length=50)),
                ('pagina', models.CharField(max_length=100)),
            ],
        ),
    ]
