# Generated by Django 5.2 on 2025-04-29 02:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_contas', '0002_submenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conta',
            name='valor',
        ),
        migrations.AlterField(
            model_name='conta',
            name='data_vencimento',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Dia de Vencimento'),
        ),
    ]
