# Generated by Django 5.2 on 2025-04-29 03:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_contas', '0003_remove_conta_valor_alter_conta_data_vencimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contaembutida',
            name='data_pagamento',
        ),
        migrations.AddField(
            model_name='contaembutida',
            name='ativa',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contaembutida',
            name='data_vencimento',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Dia de Vencimento'),
        ),
    ]
