# Generated by Django 5.2 on 2025-05-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_contas', '0004_remove_contaembutida_data_pagamento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competencia',
            options={'ordering': ['ano', 'mes']},
        ),
        migrations.RemoveField(
            model_name='competencia',
            name='data_abertura',
        ),
        migrations.RemoveField(
            model_name='competencia',
            name='data_fechamento',
        ),
        migrations.AlterField(
            model_name='competencia',
            name='mes',
            field=models.CharField(choices=[('1', 'Janeiro'), ('2', 'Fevereiro'), ('3', 'Março'), ('4', 'Abril'), ('5', 'Maio'), ('6', 'Junho'), ('7', 'Julho'), ('8', 'Agosto'), ('9', 'Setembro'), ('10', 'Outubro'), ('11', 'Novembro'), ('12', 'Dezembro')], max_length=2),
        ),
    ]
