# Generated by Django 5.2 on 2025-05-02 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_contas', '0005_alter_competencia_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competencia',
            old_name='aberta',
            new_name='ativa',
        ),
    ]
