# Generated by Django 5.2 on 2025-05-06 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_contas', '0006_rename_aberta_competencia_ativa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contapaga',
            name='conta_embutida',
        ),
        migrations.AlterField(
            model_name='itemcontaembutida',
            name='conta_embutida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='gestor_contas.conta'),
        ),
        migrations.RemoveField(
            model_name='contapaga',
            name='conta_esporadica',
        ),
        migrations.DeleteModel(
            name='ContaEmbutida',
        ),
        migrations.DeleteModel(
            name='ContaEsporadica',
        ),
    ]
