# Generated by Django 5.2 on 2025-05-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_contas', '0007_remove_contapaga_conta_embutida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='mensal',
            field=models.BooleanField(default=False),
        ),
    ]
