# Generated by Django 5.2 on 2025-05-06 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_contas', '0008_conta_mensal'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='subvalor',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Subvalores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subvalores', to='gestor_contas.conta')),
            ],
        ),
    ]
