# Generated by Django 5.2 on 2025-05-10 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_contas', '0009_conta_subvalor_subvalores'),
    ]

    operations = [
        migrations.AddField(
            model_name='subvalores',
            name='conta_paga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subvalores', to='gestor_contas.contapaga'),
        ),
    ]
