# Generated by Django 5.2 on 2025-06-10 14:13

import app.gestor_contas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_contas', '0010_subvalores_conta_paga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contapaga',
            name='comprovante',
            field=models.FileField(blank=True, null=True),
        ),
    ]
