# Generated by Django 5.2 on 2025-06-10 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_contas', '0011_alter_contapaga_comprovante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contapaga',
            name='comprovante',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
